name: 'Auto Issue Assign'

on:
  issues:
    types: created

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.0
        with:
          configuration-path: '.github/auto_issue_assign.yml'
